language: node_js
node_js:
  '10'
notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
install:
  - npm install
  # npm install ionic cordova -g
script: 'true'
after_success:
# ionic cordova build android --release
deploy:
  - provider: script
    skip_cleanup: true
    script: npx semantic-release
    on:
      branch: master
